Task6/Task6/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteEntities : DbContext
    {
        public WebsiteEntities()
            : base("name=WebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USER> USERS { get; set; }
    }
}

Task6/Task6/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Orange\source\repos\Task6\Task6\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Task6/Task6/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Task6/Task6/Models/USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int UsersID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserImage { get; set; }

        public string ConfirmPassword { get; set; }

    }
}

Task6/Task6/Controllers/CodersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task6.Models;

namespace Task6.Controllers
{
    public class CodersController : Controller
    {

        WebsiteEntities db = new WebsiteEntities();
        // GET: Coders
        public ActionResult Index()
        {
            return View();
        }

        //Regester
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "UsersID,UserName,UserEmail,UserPassword,UserImage, ConfirmPassword")] USER uSER, string confirmpassowrd)
        {
            if (ModelState.IsValid && uSER.UserPassword == confirmpassowrd)
            {
                db.USERS.Add(uSER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uSER);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(USER uSER)
        {
            var checkInputs = db.USERS.Where(model => model.UserEmail == uSER.UserEmail && model.UserPassword == uSER.UserPassword).FirstOrDefault();

            Session["UserID"] = checkInputs.UsersID;
            

            if (checkInputs != null) { 
               return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult Logout()
        {
            Session["UserID"] = null;
            return RedirectToAction("Index");
        }


        public ActionResult Profile()
        {
             var userID = (int)Session["UserID"];
             var user = db.USERS.Find(userID);
             return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Profile(USER uSER, HttpPostedFileBase upload)
        {
            

            if (upload != null && upload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(upload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);

                if (!Directory.Exists(Server.MapPath("~/Images/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Images/"));
                }

                upload.SaveAs(path);
                uSER.UserImage = fileName;
            }

            db.Entry(uSER).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult ResetPasswordt()
        {
            var userID = (int)Session["UserID"];
            var user = db.USERS.Find(userID);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPasswordt(string currentPassword, string newPassword, string confirmNewPassword)
        {
            var userID = (int)Session["UserID"];
            var user = db.USERS.Find(userID);

            if (currentPassword == user.UserPassword)
            {
                if (newPassword == confirmNewPassword)
                {
                    user.UserPassword = newPassword;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Profile");
                }
                else
                {
                    ViewBag.Message = "New Password does not match Confirm Password!";
                    return View(user);
                }
            }
            else
            {
                ViewBag.Message = "Current Password is incorrect!";
                return View(user);
            }
        }
    }
}

Task6/Task6/Views/Coders/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Home Page</h1>

Task6/Task6/Views/Coders/Login.cshtml
@model Task6.Models.USER

@{
    ViewBag.Title = "Login";
}

<h2>Log In</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label>Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Password</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default  btn-success" />

            </div>
        </div>
    </div>
}

Task6/Task6/Views/Coders/Profile.cshtml
@model Task6.Models.USER

@{
    ViewBag.Title = "Profile";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
            alert('@ViewBag.Message');
    </script>
}

<h2>Profile</h2>

@using (Html.BeginForm("Profile", "Coders", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UsersID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <img src="~/Images/@Model.UserImage" alt="Alternate Text" width="100" height="100" />
        </div>
        <div class="form-group">
            <label>Image</label>

            <div class="col-md-10">
                <input type="file" name="upload" value="" />
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.ActionLink("Reset Password", "ResetPasswordt", "Coders", new { area = "" }, new { @class = "btn btn-info" })
        </div>


        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Task6/Task6/Views/Coders/Register.cshtml
@model Task6.Models.USER

@{
    ViewBag.Title = "Register";
}

<h2>Sign Up</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        <label>Confirm Password</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <label>Confirm Password</label>
        <div class="col-md-10">
            <input type="text" name="confirmpassowrd" class="form-control" />
        </div>
    </div>

    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")


    @Html.ActionLink("Login", "Login", new { id = Model.UsersID }) |

</div>

Task6/Task6/Views/Coders/ResetPasswordt.cshtml
@model Task6.Models.USER

@{
    ViewBag.Title = "ResetPasswordt";
}

<h2>Reset Password</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UsersID)

        <div class="form-group">
            <label>Current Password</label>
            <div class="col-md-10">
                <input type="password" name="currentPassword" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label>New Password</label>
            <div class="col-md-10">
                <input type="password" name="newPassword" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label>Confirm New Password</label>
            <div class="col-md-10">
                <input type="password" name="confirmNewPassword" class="form-control" />
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}